spring:
  application:
    name: vote-app
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5435/vote_db
    username: user
    password: password
    driverClassName: org.postgresql.Driver


